# Generated by Django 2.0.3 on 2018-04-04 12:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(1), verbose_name='Сколько продлится?'),
        ),
        migrations.AddField(
            model_name='post',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Когда?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания (сохранения)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Что? (до 150 сиволов)'),
        ),
    ]
