# Generated by Django 2.0.3 on 2018-04-05 12:06

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180404_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='post',
            name='when',
        ),
        migrations.AddField(
            model_name='post',
            name='begin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Когда начнется?'),
        ),
        migrations.AddField(
            model_name='post',
            name='end',
            field=models.DateField(default=blog.models.Post.get_default_date, verbose_name='Когда закончится?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
