# Generated by Django 2.0.3 on 2018-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180407_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='best',
            field=models.BooleanField(default=False, verbose_name='Лучшее'),
        ),
    ]
